server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/lms_database}

# Multipart config for file storage
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Enable logging for debugging
logging.level.org.springframework.web=DEBUG
